version: '3'
services:
    server:
        network_mode: host
        build: server/
        ports:
          - 5000:5000
    client:
        network_mode: host
        build: client/
        command: python client.py
        